#!/bin/sh

mount -t proc proc proc

/sbin/ifconfig lo 127.0.0.1 up

mount -t ramfs ramfs /ramdisk
mkdir -m 777 /ramdisk/var
mkdir -m 777 /ramdisk/var/run
mkdir -m 777 /ramdisk/var/log
mkdir -m 777 /ramdisk/tmp
mkdir -m 777 /ramdisk/tmp/pub
mkdir -m 777 /ramdisk/optlog
mkdir -m 777 /ramdisk/smb

mount -t jffs2 -o noatime /dev/nandjffs /jffs

/etc/init.d/Srandom

/sbin/insmod /modules/audiodev.o

/wifi/netstartd --resetcheckonly

if [ -f /jffs/Configure ]; then
  echo "Running custom Configure..."
  exec /jffs/Configure
fi

if [ -f /jffs/m16_upgrade.mot ]; then
    /usr/bin/flash_zp_m16 /jffs/m16_upgrade.mot
	rm /jffs/m16_upgrade.mot
    /sbin/reboot
else
    /usr/bin/zp_in_flash_mode
    if [ $? -eq 1 ]; then
        /usr/bin/flash_zp_m16 /modules/ZP-M16.emergency.mot
        /sbin/reboot
    fi
fi

echo 262143 > /proc/sys/net/core/rmem_max
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

WIFITYPE=`mdputil | /usr/sbin/keyval ^WIFITYPE`

/sbin/insmod /wifi/$WIFITYPE/ath_hal.o
/sbin/insmod /wifi/$WIFITYPE/ath_driver.o

if [ -e /wifi/bridge.o ]; then
    /sbin/insmod /wifi/bridge.o
fi

/usr/sbin/setmac

/sbin/ifconfig eth0 0.0.0.0

touch /var/run/waitforip

if [ -f /etc/unlocked_build_flag -o -e /jffs/system/Configure.dev ]; then
    /etc/init.d/inetd start

    ln -s /opt/htdocs_locked /tmp/htdocs_locked

    touch /tmp/device_unlocked_flag
fi

if [ -f /jffs/system/Configure.dev ]; then
    sh /jffs/system/Configure.dev
fi

if [ -f /jffs/hosts ]; then
    touch /jffs/hosts
else
    cp /etc/hosts.orig /jffs/hosts
fi

/opt/bin/smbscand &

echo "Configure script complete."
