#!/bin/sh
while [ -f /var/run/waitforip ]; do
    sleep 1
done
if [ -f /var/run/upgradeurl ]; then
    mkdir /tmp
    rm /jffs/upgrade_tmp_prev.log
    mv /tmp/upgrade.log /jffs/upgrade_tmp_prev.log
    echo -n "Upgrade parameters are: " > /tmp/upgrade.log
    cat /var/run/upgradeurl >> /tmp/upgrade.log
    echo >> /tmp/upgrade.log
    echo Running upgrade ...
    /bin/upgrade -ZN `cat /var/run/upgradeurl` >> /tmp/upgrade.log 2>&1
    rr=$?
    echo RESULT = $rr >> /tmp/upgrade.log
    rm /var/run/upgradeurl
    exit $rr
fi
for X in /tmp/smb/*
do 
    if [ -d "$X" ] 
    then
        umount "$X"
        rmdir "$X"
    fi
done
while [ -f /var/run/stopanacapa ]; do
    sleep 10
done
exec /opt/bin/anacapactl start-demo
